# mongo:
	# docker run --rm -it -p 27017:27107 --name mongo -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=1234 mongo
	# docker run --rm -it -p 8000:27107 --name mongo mongo

app:
	uvicorn main:app --reload --port=8080
